import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, BookOpen, Check, ChevronRight, Database, Download, Eye, EyeOff, FolderOpen, KeyRound, LoaderCircle, ShieldCheck, SlidersHorizontal, Sparkles, Upload, X, Zap } from 'lucide-react';
import type { ProviderConfig, ProviderId, Settings } from '../../shared/types';
import { useI18n } from '../i18n';
import UpdatePanel from './UpdatePanel';
import './ui-components.css';

type UiNotice = { zh: string; en: string; values?: Record<string, string | number> };
interface Props { initialSection?: 'updates'; settings: Settings; onClose: () => void; onSaved: (settings: Settings) => void; onRefresh: () => void; onError: (message: string) => void }
function Toggle({ checked, onChange, label, description }: { checked: boolean; onChange: (checked: boolean) => void; label: string; description: string }) {
  return <div className="fl-toggle-row"><div><strong>{label}</strong><p>{description}</p></div><button type="button" className={`fl-toggle ${checked ? 'checked' : ''}`} role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)}><i /></button></div>;
}

export default function SettingsModal({ settings, onClose, onSaved, onRefresh, onError, initialSection }: Props) {
  const { t } = useI18n();
  const PROVIDERS: { id: ProviderId; title: string; subtitle: string }[] = [{ id: 'deepseek', title: 'DeepSeek', subtitle: 'Flash / Pro' }, { id: 'openai', title: 'OpenAI', subtitle: t("GPT 系列", "GPT models") }, { id: 'anthropic', title: 'Anthropic', subtitle: t("Claude 系列", "Claude models") }, { id: 'custom', title: t("自定义", "Custom"), subtitle: t("兼容 OpenAI", "OpenAI compatible") }];
  const SECTIONS = [{ id: 'ai', label: t("AI 阅读助手", "AI assistant"), icon: Sparkles }, { id: 'reading', label: t("阅读偏好", "Reading"), icon: BookOpen }, { id: 'obsidian', label: 'Obsidian', icon: FolderOpen }, { id: 'data', label: t("数据与备份", "Data & backup"), icon: Database }, { id: 'updates', label: t('应用更新', 'Updates'), icon: Download }] as const;
  const [draft, setDraft] = useState<Settings>(() => ({ ...settings, language: settings.language ?? 'zh-CN', autoCheckUpdates: settings.autoCheckUpdates ?? true, annotationToolbar: settings.annotationToolbar ?? 'floating', providers: Object.fromEntries(Object.entries(settings.providers).map(([key, config]) => [key, { ...config, apiKey: undefined }])) as Settings['providers'] }));
  const [section, setSection] = useState<(typeof SECTIONS)[number]['id']>(initialSection ?? 'ai');
  useEffect(() => { if (initialSection) setSection(initialSection); }, [initialSection]);
  const [provider, setProvider] = useState<ProviderId>(settings.activeProvider);
  const [showKey, setShowKey] = useState(false);
  const [busy, setBusy] = useState('');
  const [notice, setNotice] = useState<UiNotice | null>(null);
  const [error, setError] = useState('');
  const modalRef = useRef<HTMLDivElement>(null);
  const providerConfig = draft.providers[provider];
  const patchProvider = (patch: Partial<ProviderConfig>) => setDraft(previous => ({ ...previous, providers: { ...previous.providers, [provider]: { ...previous.providers[provider], ...patch } } }));
  useEffect(() => {
    const previous = document.activeElement as HTMLElement | null;
    modalRef.current?.focus();
    const handler = (event: KeyboardEvent) => {
      if (event.key === 'Escape' && !busy) { event.stopPropagation(); onClose(); }
      if (event.key !== 'Tab') return;
      const nodes = modalRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), [tabindex="0"]');
      if (!nodes?.length) return;
      const first = nodes[0]; const last = nodes[nodes.length - 1];
      if (event.shiftKey && (document.activeElement === first || document.activeElement === modalRef.current)) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener('keydown', handler, true);
    return () => { document.removeEventListener('keydown', handler, true); previous?.focus(); };
  }, [onClose, busy]);

  const run = async (name: string, action: () => Promise<void>) => {
    setBusy(name); setError(''); setNotice(null);
    try { await action(); } catch (cause) { const message = cause instanceof Error ? cause.message : String(cause); setError(message); onError(message); }
    finally { setBusy(''); }
  };
  const save = () => run('save', async () => {
    for (const config of Object.values(draft.providers)) {
      if (!config.baseURL.trim()) throw new Error(t("请填写 API Base URL。", "Enter an API base URL."));
      let url: URL; try { url = new URL(config.baseURL); } catch { throw new Error(t("API Base URL 需要是完整的网址。", "The API base URL must be a complete URL.")); }
      if (!['https:', 'http:'].includes(url.protocol)) throw new Error(t("API 地址必须使用 HTTP 或 HTTPS。", "The API URL must use HTTP or HTTPS."));
      if (config.id === draft.activeProvider && !config.model.trim()) throw new Error(t("请填写当前服务商的模型 ID。", "Enter a model ID for the active provider."));
      if (!Number.isFinite(config.maxTokens) || config.maxTokens < 256 || config.maxTokens > 393216) throw new Error(t("最大输出长度应在 256 到 393216 tokens 之间。", "Maximum output must be between 256 and 393216 tokens."));
    }
    if (!Number.isFinite(draft.contextMaxChars) || draft.contextMaxChars < 10000 || draft.contextMaxChars > 1500000) throw new Error(t("上下文长度应在 10000 到 1500000 字符之间。", "The context limit must be between 10000 and 1500000 characters."));
    const next = await window.folio.saveSettings(draft);
    setDraft(next); onSaved(next); setNotice({ zh: "偏好设置已保存", en: "Preferences saved" });
  });

  return <div className="fl-modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget && !busy) onClose(); }}>
    <div className="fl-settings-modal" ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="fl-settings-title" tabIndex={-1}>
      <header className="fl-settings-header"><div className="fl-settings-title-icon"><SlidersHorizontal size={19} /></div><div><h2 id="fl-settings-title">{t("把 Folio 调成你的样子", "Make Folio your own")}</h2><p>{t("一点偏好，更好的阅读体验。", "Small preferences. Better reading.")}</p></div><button className="fl-icon-button" onClick={onClose} aria-label={t("关闭设置", "Close settings")} disabled={!!busy}><X size={19} /></button></header>
      <div className="fl-settings-body"><nav className="fl-settings-nav" aria-label={t("设置分类", "Settings categories")}>{SECTIONS.map(item => <button key={item.id} className={section === item.id ? 'active' : ''} onClick={() => setSection(item.id)}><item.icon size={16} />{item.label}{section === item.id && <ChevronRight size={13} />}</button>)}<div className="fl-settings-local"><ShieldCheck size={19} /><span>{t("属于你的研究空间", "Your research space")}</span><p>{t("论文和笔记保存在本机。", "Papers and notes stay on this device.")}<br />{t("API 密钥由系统加密保存。", "API keys are encrypted by your system.")}</p></div></nav>
        <div className="fl-settings-content">
          <label className="fl-field fl-language-setting"><span>语言 / Language</span><select aria-label="语言 / Language" aria-describedby="fl-language-help" value={draft.language} disabled={!!busy} onChange={event => setDraft(previous => ({ ...previous, language: event.target.value as Settings['language'] }))}><option value="zh-CN">简体中文</option><option value="en">English</option></select><small id="fl-language-help">{t('保存后立即切换界面语言；已有论文、对话和笔记保持原文。', 'Changes take effect when saved. Existing papers, conversations, and notes keep their original text.')}</small></label>
          <div className="fl-settings-divider" />
          {section === 'updates' && <UpdatePanel autoCheckUpdates={draft.autoCheckUpdates} onAutoCheckUpdatesChange={enabled => setDraft(previous => ({ ...previous, autoCheckUpdates: enabled }))} disabled={!!busy} />}
          {section === 'ai' && <>
            <div className="fl-section-heading"><span className="fl-eyebrow">YOUR READING COMPANION</span><h3>{t("让好问题，有更深的回答。", "Take your questions further.")}</h3><p>{t("连接你自己的模型账号，阅读时随时展开讨论。", "Connect your own AI account to discuss papers as you read.")}</p></div>
            <div className="fl-provider-grid">{PROVIDERS.map(item => <button className={provider === item.id ? 'active' : ''} key={item.id} onClick={() => { setProvider(item.id); setShowKey(false); }}><span>{item.id === 'deepseek' ? <Zap size={16} /> : <Sparkles size={15} />}{draft.activeProvider === item.id && <Check size={12} />}</span><strong>{item.title}</strong><small>{item.subtitle}</small></button>)}</div>
            <div className="fl-provider-active"><span>{draft.activeProvider === provider ? <><span className="fl-small-dot" /> {t("当前使用的服务商", "Active provider")}</> : t("此服务商有独立的密钥和模型配置", "This provider has separate key and model settings")}</span>{draft.activeProvider !== provider && <button onClick={() => setDraft(previous => ({ ...previous, activeProvider: provider }))}>{t("设为默认", "Set as default")}</button>}</div>
            <label className="fl-field"><span>API Key <span className="fl-field-badge"><KeyRound size={10} /> {t("仅在本机保存", "Stored on this device")}</span></span><div className="fl-key-input"><input aria-label="API Key" type={showKey ? 'text' : 'password'} autoComplete="off" spellCheck={false} value={providerConfig.apiKey ?? ''} onChange={event => patchProvider({ apiKey: event.target.value || undefined })} placeholder={providerConfig.hasKey ? t("已保存密钥 · 留空保留现有密钥", "Key saved · leave blank to keep it") : t("粘贴你的 API Key", "Paste your API key")} /><button className="fl-icon-button" onClick={() => setShowKey(!showKey)} aria-label={showKey ? t("隐藏输入的密钥", "Hide entered key") : t("显示输入的密钥", "Show entered key")}>{showKey ? <EyeOff size={15} /> : <Eye size={15} />}</button></div><small>{t("密钥不会写入笔记或备份。", "Keys are excluded from notes and backups.")}{' '}{providerConfig.hasKey ? t("输入新密钥后保存，即可替换。", "Enter a new key and save to replace it.") : t("你可以从服务商的开发者平台创建密钥。", "Create a key on your provider’s developer platform.")}</small></label>
            <label className="fl-field"><span>API Base URL</span><input aria-label="API Base URL" type="url" value={providerConfig.baseURL} onChange={event => patchProvider({ baseURL: event.target.value })} spellCheck={false} /></label>
            {provider === 'deepseek' && <><label className="fl-field"><span>{t("DeepSeek 模型", "DeepSeek model")}</span><div className="fl-model-options">{[{ model: 'deepseek-flash', title: 'Flash', subtitle: t("日常问答，快速理解", "Fast, everyday paper questions") }, { model: 'deepseek-v4-pro', title: 'Pro', subtitle: t("复杂推理，深入分析", "Complex reasoning and analysis") }].map(item => <button key={item.model} className={providerConfig.model === item.model ? 'active' : ''} onClick={() => patchProvider({ model: item.model })}><span><strong>{item.title}</strong>{providerConfig.model === item.model && <Check size={14} />}</span><small>{item.subtitle}</small></button>)}</div></label><Toggle checked={providerConfig.thinking !== false} onChange={checked => patchProvider({ thinking: checked })} label={t("深度思考", "Thinking mode")} description={t("启用模型思考模式，更仔细地分析论文与问题。", "Enable reasoning for a closer analysis of papers and questions.")} />{providerConfig.thinking !== false && <label className="fl-field"><span>{t("思考深度", "Thinking depth")}</span><select aria-label={t("思考深度", "Thinking depth")} value={providerConfig.reasoningEffort ?? 'high'} onChange={event => patchProvider({ reasoningEffort: event.target.value as 'low' | 'high' | 'max' })}><option value="low">{t("低 · Low", "Low")}</option><option value="high">{t("高 · High（默认）", "High (default)")}</option><option value="max">{t("最高 · Max", "Max")}</option></select><small>{t("更高的深度可能需要更多响应时间与 tokens。", "Higher depth may take longer and use more tokens.")}</small></label>}<button className="fl-text-link" onClick={() => void window.folio.openExternal('https://api-docs.deepseek.com/guides/thinking_mode/').catch(error => onError(String(error)))}>{t("查看 DeepSeek 官方思考模式文档", "DeepSeek thinking-mode documentation")} <ArrowUpRight size={12} /></button></>}
            <div className="fl-field-pair"><label className="fl-field"><span>{t("模型 ID", "Model ID")}</span><input aria-label={t("模型 ID", "Model ID")} value={providerConfig.model} onChange={event => patchProvider({ model: event.target.value })} spellCheck={false} /><small>{t("可直接填写服务商支持的模型名称。", "Enter a model name supported by this provider.")}</small></label><label className="fl-field"><span>{t("最大输出 tokens", "Maximum output tokens")}</span><input aria-label={t("最大输出 tokens", "Maximum output tokens")} type="number" min={256} max={393216} step={256} value={providerConfig.maxTokens} onChange={event => patchProvider({ maxTokens: Number(event.target.value) })} /></label></div>
            <div className="fl-settings-divider" />
            <Toggle label={t("自动生成论文摘要", "Automatic paper summaries")} description={t("首次打开已完成文本索引的论文时，自动请求 AI 摘要，会产生 API 费用。", "Request a summary when an indexed paper is first opened. This incurs API charges.")} checked={draft.autoSummary} onChange={checked => setDraft(previous => ({ ...previous, autoSummary: checked }))} />
            <Toggle label={t("自动积累阅读记忆", "Automatic reading memory")} description={t("从对话中提炼发现与问题，供后续阅读调用；会产生额外 API 请求。", "Extract findings and questions from conversations for future reading. This makes additional API requests.")} checked={draft.autoMemory} onChange={checked => setDraft(previous => ({ ...previous, autoMemory: checked }))} />
            <label className="fl-field"><span>{t("单次论文上下文上限（字符）", "Paper context limit (characters)")}</span><input aria-label={t("单次论文上下文上限（字符）", "Paper context limit (characters)")} type="number" min={10000} max={1500000} step={10000} value={draft.contextMaxChars} onChange={event => setDraft(previous => ({ ...previous, contextMaxChars: Number(event.target.value) }))} /><small>{t("更长的上下文可容纳更多正文与补充材料，也会增加 token 用量。", "A longer context includes more paper and supplement text, using more tokens.")}</small></label>
          </>}
          {section === 'reading' && <><div className="fl-section-heading"><span className="fl-eyebrow">MAKE ROOM FOR FOCUS</span><h3>{t("舒适一点，读得久一点。", "Settle in for a closer read.")}</h3><p>{t("选择舒适的界面配色与常用批注工具的位置。", "Choose your appearance and annotation toolbar position.")}</p></div><label className="fl-field"><span>{t("应用外观", "Appearance")}</span><div className="fl-theme-options">{[{ value: 'light', title: t("浅色", "Light"), className: 'light' }, { value: 'dark', title: t("深色", "Dark"), className: 'dark' }].map(item => <button key={item.value} className={`${item.className} ${draft.theme === item.value ? 'active' : ''}`} onClick={() => setDraft(previous => ({ ...previous, theme: item.value as Settings['theme'] }))}><i><span /><span /></i><strong>{item.title}</strong>{draft.theme === item.value && <Check size={14} />}</button>)}</div></label><label className="fl-field"><span>{t("PDF 纸张", "PDF page colors")}</span><div className="fl-paper-themes">{[{ value: 'white', title: t("原纸", "Original"), color: '#ffffff' }, { value: 'sepia', title: t("暖纸", "Sepia"), color: '#f4e6cb' }, { value: 'dark', title: t("夜读", "Night"), color: '#25282b' }].map(item => <button key={item.value} className={draft.readingTheme === item.value ? 'active' : ''} onClick={() => setDraft(previous => ({ ...previous, readingTheme: item.value as Settings['readingTheme'] }))}><i style={{ background: item.color }} /><span>{item.title}</span>{draft.readingTheme === item.value && <Check size={13} />}</button>)}</div><small>{t("阅读配色只影响显示，导出 PDF 保持原始颜色。", "These colors affect reading only. Exported PDFs keep their original colors.")}</small></label>
            <label className="fl-field"><span>{t("批注工具栏", "Annotation toolbar")}</span><select aria-label={t("批注工具栏位置", "Annotation toolbar position")} aria-describedby="fl-annotation-toolbar-help" value={draft.annotationToolbar ?? 'floating'} onChange={event => setDraft(previous => ({ ...previous, annotationToolbar: event.target.value as Settings['annotationToolbar'] }))}><option value="floating">{t("底部悬浮（常驻）", "Floating at bottom (always visible)")}</option><option value="fixed">{t("顶部固定（常驻）", "Fixed at top (always visible)")}</option><option value="selection">{t("仅选中文字时显示", "Show only when text is selected")}</option></select><small id="fl-annotation-toolbar-help">{t("所有阅读区共用一个工具栏，操作作用于当前阅读区。常驻模式下，可先选择荧光笔与颜色；复制等操作需要先选中文字。", "One toolbar controls the active reading pane. In always-visible mode, choose a marker and color before selecting text. Copying and similar actions require a text selection.")}</small></label>
          </>}
          {section === 'obsidian' && <><div className="fl-section-heading"><span className="fl-eyebrow">CONNECT YOUR KNOWLEDGE</span><h3>{t("让笔记，回到你的知识库。", "Bring notes into your knowledge base.")}</h3><p>{t("摘要、个人笔记、阅读记忆与对话，整理成 Markdown。", "Export summaries, personal notes, memories, and conversations as Markdown.")}</p></div><div className="fl-obsidian-card"><div className="fl-obsidian-gem">◇</div><div><strong>Folio → Obsidian</strong><p>{t("在阅读助手中一键导出，保留论文来源。", "Export from the reading assistant with links to the paper.")}</p></div></div><label className="fl-field"><span>{t("Obsidian Vault 文件夹", "Obsidian vault folder")}</span><div className="fl-folder-picker"><input aria-label={t("Obsidian Vault 文件夹", "Obsidian vault folder")} readOnly value={draft.vaultPath} placeholder={t("选择现有的 Obsidian 知识库", "Choose an existing Obsidian vault")} /><button className="fl-button fl-secondary" disabled={!!busy} onClick={() => void run('folder', async () => { const path = await window.folio.pickFolder('vault'); if (path) setDraft(previous => ({ ...previous, vaultPath: path })); })}><FolderOpen size={15} /> {t("选择", "Choose")}</button></div></label><label className="fl-field"><span>{t("笔记保存到子文件夹", "Notes subfolder")}</span><input aria-label={t("笔记保存到子文件夹", "Notes subfolder")} value={draft.obsidianSubfolder} onChange={event => setDraft(previous => ({ ...previous, obsidianSubfolder: event.target.value }))} placeholder="Papers" /><small>{t("可填写 Papers/阅读笔记；导出时会自动创建。", "For example, Papers/Reading notes. Created automatically on export.")}</small></label><div className="fl-info-note"><FileIcon /><p>{t("导出使用论文标题命名。再次导出只更新 Folio 生成区域，保留你在该区域之外添加的内容。", "Exports use the paper title. Later exports update only the Folio section, preserving content you add outside it.")}</p></div>{draft.vaultPath && <button className="fl-button fl-quiet" onClick={() => setDraft(previous => ({ ...previous, vaultPath: '' }))}>{t("取消关联此知识库", "Unlink this vault")}</button>}</>}
          {section === 'data' && <><div className="fl-section-heading"><span className="fl-eyebrow">LOCAL FIRST, ALWAYS YOURS</span><h3>{t("你的论文，由你保管。", "Your papers, in your hands.")}</h3><p>{t("打包工作区，或把原来阅读助手中的记录带过来。", "Back up workspaces or bring in records from an earlier reading assistant.")}</p></div><label className="fl-field"><span>{t("文献库位置", "Library location")}</span><input aria-label={t("文献库位置", "Library location")} readOnly value={draft.libraryPath} /><small>{t("每篇论文拥有独立文件夹，正文与补充材料保存在一起。", "Each paper has its own folder for the main text and supplements.")}</small></label><div className="fl-data-action"><span className="fl-data-icon"><Download size={20} /></span><div><strong>{t("导出文献库备份", "Export library backup")}</strong><p>{t("包含 PDF、笔记、对话和阅读进度，不包含 API 密钥。", "Includes PDFs, notes, conversations, and reading progress. Excludes API keys.")}</p></div><button className="fl-button fl-secondary" disabled={!!busy} onClick={() => void run('backup', async () => { const result = await window.folio.backup(); if (result) setNotice({ zh: "备份已保存：{path}", en: "Backup saved: {path}", values: { path: result.path } }); })}>{busy === 'backup' ? <LoaderCircle size={15} className="fl-spin" /> : t("导出", "Export")}</button></div><div className="fl-data-action"><span className="fl-data-icon"><Upload size={20} /></span><div><strong>{t("从备份恢复", "Restore from backup")}</strong><p>{t("选择 Folio 备份文件，将工作区导入到文献库。", "Import workspaces from a Folio backup file.")}</p></div><button className="fl-button fl-secondary" disabled={!!busy} onClick={() => void run('restore', async () => { const result = await window.folio.restore(); if (result) { setNotice({ zh: "已恢复 {count} 个工作区", en: "Restored {count} workspaces", values: { count: result.count } }); onRefresh(); } })}>{busy === 'restore' ? <LoaderCircle size={15} className="fl-spin" /> : t("恢复", "Restore")}</button></div><div className="fl-data-action"><span className="fl-data-icon lavender"><Sparkles size={20} /></span><div><strong>{t("导入原阅读助手数据", "Import legacy reading data")}</strong><p>{t("选择 Paper Reading Assistant 导出的 JSON 备份。", "Choose a JSON backup exported by Paper Reading Assistant.")}</p></div><button className="fl-button fl-secondary" disabled={!!busy} onClick={() => void run('legacy', async () => { const result = await window.folio.importLegacy(); if (result) { setNotice({ zh: "已导入 {count} 篇论文的阅读记录", en: "Imported reading records for {count} papers", values: { count: result.count } }); onRefresh(); } })}>{busy === 'legacy' ? <LoaderCircle size={15} className="fl-spin" /> : t("导入", "Import")}</button></div></>}
        </div>
      </div>
      <footer className="fl-settings-footer"><div role="status" className={error ? 'fl-error-text' : 'fl-save-notice'}>{error || (notice ? <><Check size={14} />{t(notice.zh, notice.en, notice.values)}</> : <><ShieldCheck size={14} /> {t("偏好设置仅保存在本机", "Preferences stay on this device")}</>)}</div><button className="fl-button fl-secondary" onClick={onClose} disabled={!!busy}>{t("关闭", "Close")}</button><button className="fl-button fl-primary" disabled={!!busy} onClick={() => void save()}>{busy === 'save' ? <LoaderCircle size={15} className="fl-spin" /> : <Check size={15} />} {t("保存设置", "Save settings")}</button></footer>
    </div>
  </div>;
}
function FileIcon() { return <BookOpen size={18} />; }
